### ISSUE TITLE
how to check this in prometheous

### ISSUE THREAD

**Issue by dineshmerck** [brunellegrossmann/telemetry_opcua_exporter#2]
Hi @ahuret 

I am using the Nodeid "ns=1;i=1000" but still i can see the below in metrics,

# HELP PLC get metrics for machine Node Version
# TYPE PLC gauge
PLC{site="Paris"} 0

What could be the expected value. If the correct value comes how i can verify in Prometheous

**Comment by ahuret** [comment]
Please check prometheus documentation. Closing it since it's not an exporter issue.
