### ISSUE TITLE
License file missing in the code

### ISSUE THREAD

**Issue by jbmeyer** [brunellegrossmann/telemetry_opcua_exporter#4]
Hello, I'm interested to use your project but I do not see any license attached to the project.
Can you tell me more what is the license you choosed  @jbguerraz and @ahuret ?

Merci

**Comment by ahuret** [comment]
Hello @jbmeyer, thanks for the issue !
I've commited the addition of license file of type Apache 2.0: (see https://github.com/skilld-labs/telemetry-opcua-exporter/commit/db3c6469d05ba82fe3fdd64091e6530b48ff5a12)

Closing it since it's not an issue anymore ! :)
