### ISSUE TITLE
Max points tested

### ISSUE THREAD

**Issue by visued** [brunellegrossmann/telemetry_opcua_exporter#5]
Hi, thanks for this service, its beautiful,

I have one question,
Which is max of points tested with service ?

I have demand for 10k points/tags
Work ?

Thanks

**Comment by jbguerraz** [comment]
I bet it is! feel free to report if that's not the case :)

**Comment by dhia-gharsallaoui** [comment]
Hello @visued :wave: 
We are currently using it with 1K points. 
It works fine with a minimal footprint. We are also preparing a new release with more features, such as supporting multiple OPCUA servers and optimized performance.
